### ISSUE TITLE
Reading assumed real value 'cf_null', anomalous remainder '' 

### ISSUE THREAD

**Issue by leoliu** [cfengine/masterfiles#413]
Running the `3.6.x` branch with cfengine 3.6.3 on centos 7, I am seeing many such errors lately:

2015-01-25T10:03:51+0800    error: /default/cfe_internal_cleanup_agent_reports/vars/'total_report_size'[0]: Reading assumed real value 'cf_null', anomalous remainder ''

**Comment by nickanderson** [comment]
Thanks for the report @leoliu.

In the future please submit issues to redmine at dev.cfengine.com.

Thanks!

**Comment by leoliu** [comment]
Hi @nickanderson,

I can do that but unfortunately all these bug trackers require registration and give me a headache :(

Leo
