### ISSUE TITLE
package_basename in package_specific doesn't work with dpkg_version

### ISSUE THREAD

**Issue by smotti** [cfengine/masterfiles#431]
Note I tried that only on Debian.

The installation of debian packages (.deb) doesn't work with the
package_specific() bundle defined in lib/3.6/packages.cf. The reason for this 
seems the way how the package_basename is retrieved.

Currently the package_basename is retrieved like this:

```
vars:
  "package_basename" string => lastnode("${package_name}", "/");
````

If the package_name is "/var/cfengine/packages/influxdb_0.8.8_amd64.deb" the
resulting package_basename is "influxdb_0.8.8_amd64.deb". This one is used
in the packages promise that follows below.

```
packages:
  debian.filebased::

    "${package_basename}"
      package_policy => ${desired},
      package_select = ">=",
      package_version => ${package_version},
      package_architectures => { ${package_arch} };
      package_method => dpkg_version(${dir});
```

And it seems like that dpkg_version() doesn't like the package_basename.
Probably because it builds up the full package_name itself:

```
body package_method dpkg_version(repo)
{
  ...

  debian.x86_64::
    package_name_convention => "${name}_${version}_amd64.deb";

  debian.i686::
    package_name_convention => "${name}_${version}_i386.deb";
}
```

I'm not sure about that but IIRC ${name} will be replaced with package_basename.

When only "influxdb" is used as package_basename it works as expected.

My current workaround:

```
bundle agent package_specific(package_name, desired, package_version, package_arch)
{
  ...

  classes:
    "extracted_basename" expression => regextract(
      "([\w\d\-]*)_.*", ${package_name}, "extracted_basename");

  ...

  packages:

    debian.filebased::

      "${extracted_basename[1]}"
        ...
}
```

I'm not a regex guru, and I think there is mostlikely a more elegant way

Thank you!

Kind regards,
smotti (namra)

**Comment by kacfengine** [comment]
Thanks, but note that we don't accept bug reports on Github. Please submit your bug report at https://dev.cfengine.com/.
