### ISSUE TITLE
The install instructions are not correct.

### ISSUE THREAD

**Issue by mbucc** [cfengine/masterfiles#446]
I downloaded 3.6.4 tarball (https://github.com/cfengine/masterfiles/releases/tag/3.6.5), and it requires that you run autogen.sh.
```bash
$ tar tzvf ~/Downloads/masterfiles-3.6.5.tar.gz  |grep configure
-rw-rw-r-- root/root      3576 2015-03-06 09:59 masterfiles-3.6.5/configure.ac
$ 
```

This is contrary to my reading of the README:

> If you have downloaded a release tarball, 
> you don't need to run autogen.sh.

**Comment by nickanderson** [comment]
I have updated the README. You need to run autogen if you download from github. If you download from our website then you don't have to run autogen, you can simply run ./configure.

Thanks for asking for clarification.
