### ISSUE TITLE
Please provide documentation for how to get master files

### ISSUE THREAD

**Issue by mbucc** [cfengine/masterfiles#447]
I understand from https://dev.cfengine.com/issues/6507 you need autoconf for building tests as well as an installed version of cfengine.

I am working in an environment where I don't permission to edit files under /var and all I want is the complete set of masterfiles.

It was not clear to me how I get them.  If I just get all cf.* files and put them together in one directory, is that sufficient?  Or do I need to preserve the directory hierarchy defined in the repo?

I understand not having time to automate this, but a simple line of documentation to install section of the README would be helpful for newcomers like me.  (I would supply a patch, but I don't know the right answer.)

**Comment by mbucc** [comment]
Looks like importing the full set of lib/3.6 files works.  Is this the correct approach?

**Comment by nickanderson** [comment]
Sorry, we don't track issues here in github.

I think this is what you were looking for:
https://github.com/cfengine/masterfiles/blob/master/README.md#installation
